import { describe, it, expect } from 'vitest';
import { generateSql } from '../index.js';
import type { Operation, PlanResult } from '../../planner/index.js';

function makeOp(overrides: Partial<Operation>): Operation {
  return {
    type: 'create_table',
    phase: 6,
    objectName: 'test',
    sql: 'CREATE TABLE "public"."test" (id integer PRIMARY KEY)',
    destructive: false,
    ...overrides,
  };
}

describe('generateSql', () => {
  it('returns empty string for empty plan', () => {
    const plan: PlanResult = { operations: [], blocked: [] };
    const result = generateSql(plan);
    expect(result).toBe('');
  });

  it('renders a single operation with semicolon and newline', () => {
    const plan: PlanResult = {
      operations: [makeOp({})],
      blocked: [],
    };
    const result = generateSql(plan);
    expect(result).toContain('CREATE TABLE "public"."test" (id integer PRIMARY KEY);');
  });

  it('renders multiple operations separated by blank lines', () => {
    const plan: PlanResult = {
      operations: [
        makeOp({ type: 'create_extension', phase: 2, objectName: 'uuid-ossp', sql: 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' }),
        makeOp({ type: 'create_table', phase: 6, objectName: 'users', sql: 'CREATE TABLE "public"."users" (\n  "id" uuid PRIMARY KEY\n)' }),
      ],
      blocked: [],
    };
    const result = generateSql(plan);
    const lines = result.split('\n');
    // Should have both statements
    expect(result).toContain('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";');
    expect(result).toContain('CREATE TABLE "public"."users"');
  });

  it('preserves operation order (already sorted by phase)', () => {
    const plan: PlanResult = {
      operations: [
        makeOp({ phase: 2, sql: 'FIRST' }),
        makeOp({ phase: 6, sql: 'SECOND' }),
        makeOp({ phase: 14, sql: 'THIRD' }),
      ],
      blocked: [],
    };
    const result = generateSql(plan);
    const firstIdx = result.indexOf('FIRST');
    const secondIdx = result.indexOf('SECOND');
    const thirdIdx = result.indexOf('THIRD');
    expect(firstIdx).toBeLessThan(secondIdx);
    expect(secondIdx).toBeLessThan(thirdIdx);
  });

  it('adds header comment with generation timestamp', () => {
    const plan: PlanResult = {
      operations: [makeOp({})],
      blocked: [],
    };
    const result = generateSql(plan);
    expect(result).toMatch(/^-- Migration generated by simplicity-schema/);
  });

  it('includes blocked operations as comments when includeBlocked is true', () => {
    const plan: PlanResult = {
      operations: [makeOp({ sql: 'CREATE TABLE "public"."users" (id integer PRIMARY KEY)' })],
      blocked: [makeOp({ type: 'drop_table', sql: 'DROP TABLE "public"."old_table" CASCADE', destructive: true })],
    };
    const result = generateSql(plan, { includeBlocked: true });
    expect(result).toContain('-- BLOCKED (destructive)');
    expect(result).toContain('-- DROP TABLE "public"."old_table" CASCADE;');
  });

  it('excludes blocked operations by default', () => {
    const plan: PlanResult = {
      operations: [makeOp({})],
      blocked: [makeOp({ type: 'drop_table', sql: 'DROP TABLE "public"."old_table" CASCADE', destructive: true })],
    };
    const result = generateSql(plan);
    expect(result).not.toContain('old_table');
  });

  it('wraps operations in a transaction when wrapInTransaction is true', () => {
    const plan: PlanResult = {
      operations: [makeOp({})],
      blocked: [],
    };
    const result = generateSql(plan, { wrapInTransaction: true });
    expect(result).toContain('BEGIN;');
    expect(result).toContain('COMMIT;');
  });

  it('does not wrap in transaction by default', () => {
    const plan: PlanResult = {
      operations: [makeOp({})],
      blocked: [],
    };
    const result = generateSql(plan);
    expect(result).not.toContain('BEGIN;');
    expect(result).not.toContain('COMMIT;');
  });

  it('does not duplicate semicolons if SQL already ends with one', () => {
    const plan: PlanResult = {
      operations: [makeOp({ sql: 'SELECT 1;' })],
      blocked: [],
    };
    const result = generateSql(plan);
    // Should not have ';;'
    expect(result).not.toContain(';;');
    expect(result).toContain('SELECT 1;');
  });

  it('adds section comments grouping operations by phase', () => {
    const plan: PlanResult = {
      operations: [
        makeOp({ type: 'create_extension', phase: 2, sql: 'CREATE EXTENSION IF NOT EXISTS "pgcrypto"' }),
        makeOp({ type: 'create_table', phase: 6, sql: 'CREATE TABLE "public"."users" (id int)' }),
        makeOp({ type: 'add_index', phase: 7, sql: 'CREATE INDEX "idx_users_email" ON "public"."users" ("email")' }),
      ],
      blocked: [],
    };
    const result = generateSql(plan);
    expect(result).toContain('-- Extensions');
    expect(result).toContain('-- Tables');
    expect(result).toContain('-- Indexes');
  });
});
