#!/usr/bin/env bash
set -euo pipefail

# Generates docs/MILESTONES.md from docs/tasks/T-*.md files.
# Includes per-task cost and per-milestone rollup.
# Usage: ./scripts/update-milestones.sh

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TASKS_DIR="$PROJECT_DIR/docs/tasks"
OUTPUT="$PROJECT_DIR/docs/MILESTONES.md"
TMPFILE=$(mktemp)

# Collect task data: milestone|check|title|cost
for f in "$TASKS_DIR"/T-*.md; do
  [[ -f "$f" ]] || continue

  title=$(head -1 "$f" | sed 's/^# //')
  status=$(grep '^\- \*\*Status\*\*:' "$f" | sed 's/.*: //')
  milestone=$(grep '^\- \*\*Milestone\*\*:' "$f" | sed 's/.*: //')
  cost=$(grep '^\- \*\*Cost\*\*:' "$f" | sed 's/.*: *//' || true)

  if [[ "$status" == "DONE" ]]; then
    echo "${milestone}|x|${title}|${cost}" >> "$TMPFILE"
  else
    echo "${milestone}| |${title}|" >> "$TMPFILE"
  fi
done

# Generate markdown, grouping by milestone in order of first appearance
{
  echo "# Milestones"
  echo ""
  echo "Quick-scan index. Source of truth is \`docs/tasks/T-NNN.md\`."
  echo ""
  echo "_Generated by \`pnpm milestones\`._"

  current_ms=""
  ms_cost="0"
  ms_buf=""

  flush_milestone() {
    if [[ -n "$ms_buf" ]]; then
      # Print milestone header with rollup cost
      if [[ "$ms_cost" != "0" && "$ms_cost" != "0.00" ]]; then
        echo ""
        echo "## ${current_ms} (\$${ms_cost})"
      else
        echo ""
        echo "## ${current_ms}"
      fi
      echo ""
      echo "$ms_buf"
    fi
  }

  while IFS='|' read -r ms check title cost; do
    if [[ "$ms" != "$current_ms" ]]; then
      flush_milestone
      current_ms="$ms"
      ms_cost="0"
      ms_buf=""
    fi

    # Build task line
    if [[ -n "$cost" ]]; then
      line="- [${check}] ${title} — ${cost}"
      # Add to milestone total (strip $ sign)
      cost_num=$(echo "$cost" | sed 's/\$//')
      ms_cost=$(awk "BEGIN {printf \"%.2f\", $ms_cost + $cost_num}")
    else
      line="- [${check}] ${title}"
    fi

    if [[ -z "$ms_buf" ]]; then
      ms_buf="$line"
    else
      ms_buf="$ms_buf
$line"
    fi
  done < "$TMPFILE"

  # Flush last milestone
  flush_milestone

  # Grand total
  grand_total=$(awk -F'|' '{
    cost = $4
    gsub(/\$/, "", cost)
    if (cost != "") total += cost
  } END {
    printf "%.2f", total
  }' "$TMPFILE")

  echo ""
  echo "---"
  echo ""
  echo "**Total cost: \$${grand_total}**"
} > "$OUTPUT"

rm -f "$TMPFILE"

done_count=$(grep -c '^\- \[x\]' "$OUTPUT" || echo 0)
todo_count=$(grep -c '^\- \[ \]' "$OUTPUT" || echo 0)
echo "Updated $OUTPUT — $done_count done, $todo_count remaining"
