#!/usr/bin/env bash
set -euo pipefail

# Generates docs/MILESTONES.md from docs/tasks/T-*.md files.
# Usage: ./scripts/update-milestones.sh

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TASKS_DIR="$PROJECT_DIR/docs/tasks"
OUTPUT="$PROJECT_DIR/docs/MILESTONES.md"
TMPFILE=$(mktemp)

# Collect task data: milestone|check|title
for f in "$TASKS_DIR"/T-*.md; do
  [[ -f "$f" ]] || continue

  title=$(head -1 "$f" | sed 's/^# //')
  status=$(grep '^\- \*\*Status\*\*:' "$f" | sed 's/.*: //')
  milestone=$(grep '^\- \*\*Milestone\*\*:' "$f" | sed 's/.*: //')

  if [[ "$status" == "DONE" ]]; then
    echo "${milestone}|x|${title}" >> "$TMPFILE"
  else
    echo "${milestone}| |${title}" >> "$TMPFILE"
  fi
done

# Generate markdown, grouping by milestone in order of first appearance
{
  echo "# Milestones"
  echo ""
  echo "Quick-scan index. Source of truth is \`docs/tasks/T-NNN.md\`."
  echo ""
  echo "_Generated by \`pnpm milestones\`._"

  current_ms=""
  while IFS='|' read -r ms check title; do
    if [[ "$ms" != "$current_ms" ]]; then
      current_ms="$ms"
      echo ""
      echo "## $ms"
      echo ""
    fi
    echo "- [${check}] ${title}"
  done < "$TMPFILE"
} > "$OUTPUT"

rm -f "$TMPFILE"

done_count=$(grep -c '^\- \[x\]' "$OUTPUT")
todo_count=$(grep -c '^\- \[ \]' "$OUTPUT")
echo "Updated $OUTPUT — $done_count done, $todo_count remaining"
