/**
 * SQL generation for simplicity-schema.
 *
 * Renders a migration plan as a standalone .sql file.
 */

import type { Operation, PlanResult } from '../planner/index.js';

export interface GenerateSqlOptions {
  /** Wrap all statements in BEGIN/COMMIT */
  wrapInTransaction?: boolean;
  /** Include blocked (destructive) operations as comments */
  includeBlocked?: boolean;
}

const PHASE_LABELS: Record<number, string> = {
  2: 'Extensions',
  3: 'Enums',
  4: 'Roles',
  5: 'Functions',
  6: 'Tables',
  7: 'Indexes',
  8: 'Foreign Keys',
  9: 'Views',
  10: 'Materialized Views',
  11: 'Triggers',
  12: 'Row-Level Security',
  13: 'Grants',
  14: 'Comments',
  15: 'Seeds',
};

/**
 * Render a migration plan as a SQL string.
 */
export function generateSql(plan: PlanResult, options: GenerateSqlOptions = {}): string {
  const { wrapInTransaction = false, includeBlocked = false } = options;

  if (plan.operations.length === 0 && (!includeBlocked || plan.blocked.length === 0)) {
    return '';
  }

  const lines: string[] = [];

  lines.push(`-- Migration generated by simplicity-schema`);
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push('');

  if (wrapInTransaction) {
    lines.push('BEGIN;');
    lines.push('');
  }

  // Group operations by phase and emit section comments
  let lastPhase = -1;
  for (const op of plan.operations) {
    if (op.phase !== lastPhase) {
      if (lastPhase !== -1) lines.push('');
      const label = PHASE_LABELS[op.phase] || `Phase ${op.phase}`;
      lines.push(`-- ${label}`);
      lastPhase = op.phase;
    }
    lines.push(addSemicolon(op.sql));
  }

  if (includeBlocked && plan.blocked.length > 0) {
    lines.push('');
    lines.push('-- BLOCKED (destructive) — uncomment to apply:');
    for (const op of plan.blocked) {
      lines.push(`-- ${addSemicolon(op.sql)}`);
    }
  }

  if (wrapInTransaction) {
    lines.push('');
    lines.push('COMMIT;');
  }

  lines.push('');
  return lines.join('\n');
}

function addSemicolon(sql: string): string {
  const trimmed = sql.trimEnd();
  return trimmed.endsWith(';') ? trimmed : `${trimmed};`;
}
